### ISSUE TITLE
Question: Bearer Token on Logout?

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/tea-taster-react#1]
I have not taken the course yet, but was just looking at the code output.

Just a question I want to look at when I do audit the course: how does the logout work with (apparently) no bearer token: https://github.com/ionic-team/tea-taster-react/blob/main/src/core/services/AuthService.ts#L26-L30

Or am I just overlooking something?

**Comment by ehorodyski-ionic** [comment]
This is an error when translating from the Angular service to React -- will fix!

**Comment by ehorodyski-ionic** [comment]
Addressed and fixed with Pull Request #3
